from regions import SkyRegion

class EventFilter():
    def __init__(self):
        ...
    
    def region(reg: SkyRegion):
        ...
    
    def time(): ...
    
    def grade(): ...
    
    def status(): ...